(() => {
  const en = {
    "网站导航": "Website navigation", "主导航": "Main navigation", "产品": "Products", "技术与能力": "Technology", "关于我们": "About us", "帮助中心": "Help Center", "提交工单": "Submit a ticket", "返回支持中心": "Back to Help Center", "官方帮助中心": "Official Help Center", "官方技术支持": "Official technical support", "查找设备、健康数据、账户、服务及系统相关的使用帮助。": "Find help for devices, health data, accounts, services, and system features.", "搜索帮助内容，例如：设备连接、健康报告、定位异常……": "Search help, e.g. device connection, health reports, location…", "搜索帮助内容": "Search help content", "清除搜索": "Clear search", "暂未找到匹配内容，请尝试更换关键词或提交支持工单。": "No matching content. Try another keyword or submit a ticket.", "帮助目录": "Help directory", "查找支持内容": "Find support content", "选择一个分类，查看对应的帮助与解决方案。": "Choose a category to browse help and solutions.", "支持内容分类": "Support categories", "官方工单服务": "Official ticket service", "没有找到需要的内容？": "Didn’t find what you need?", "如果仍未解决您的问题，我们随时为您提供帮助。": "If your issue is still unresolved, we’re here to help.", "平均响应时间：15 分钟": "Average response time: 15 minutes", "服务时间：周一至周日 9:00–22:00": "Hours: Mon–Sun, 9:00–22:00", "支持范围": "Support scope", "常见问题": "FAQ", "操作指南": "Guides", "在线支持": "Online support", "升级与维护": "Updates & maintenance", "数据安全": "Data security", "PalEcho 为用户提供覆盖设备、数据、账户及平台服务的官方支持。": "PalEcho provides official support for devices, data, accounts, and platform services.", "快速查看用户最常遇到的问题。": "Quick answers to common questions.", "从首次使用到日常管理，快速了解 PalEcho 的主要功能。": "Learn PalEcho’s core features, from setup to everyday management.", "通过官方渠道提交问题并获得帮助。": "Contact us through official channels and get help.", "查看最新版本、功能更新及维护安排。": "See the latest releases, feature updates, and maintenance notices.", "了解 PalEcho 如何保护设备数据、健康信息与账户安全。": "Learn how PalEcho protects device data, health information, and accounts.",
    "智能硬件设备": "Smart hardware", "查看设备连接、佩戴、充电及使用帮助。": "Help with connecting, wearing, charging, and using your device.", "健康助手": "Health Assistant", "了解健康分析、异常提醒及报告功能。": "Learn about health analysis, alerts, and reports.", "健康数据管理": "Health data management", "查看数据同步、健康档案和历史记录。": "Manage sync, health profiles, and history.", "数字宠物功能": "Digital pet features", "了解陪伴互动、状态记录与日常功能。": "Learn about companion interactions, status records, and daily features.", "商城与订单": "Store & orders", "处理订单查询、配送与售后相关问题。": "Help with orders, delivery, and after-sales service.", "账户与会员": "Account & membership", "管理登录信息、会员权益与账户设置。": "Manage sign-in details, membership benefits, and settings.", "定位与防丢": "Location & safety", "查看定位权限、电子围栏与防丢帮助。": "Help with location permissions, geofences, and lost-pet safety.", "系统更新": "System updates", "了解版本更新、功能变化与使用要求。": "Learn about releases, changes, and requirements.",
    "设备无法连接怎么办？": "What if my device will not connect?", "从设备电量、蓝牙权限与网络环境开始排查。": "Start with battery, Bluetooth permissions, and network conditions.", "为什么没有健康数据？": "Why is there no health data?", "检查佩戴、同步状态和账户绑定情况。": "Check wearing, sync status, and account binding.", "定位出现偏差怎么办？": "What if the location is inaccurate?", "了解定位权限与室内外环境的影响。": "Learn how permissions and indoor or outdoor conditions affect location.", "健康报告没有更新怎么办？": "Why has my health report not updated?", "确认同步状态和报告生成时间。": "Check sync status and report generation time.", "设备续航时间异常怎么办？": "Why is battery life shorter than expected?", "查看充电状态、使用环境与定位设置。": "Review charging, usage conditions, and location settings.", "账号无法登录怎么办？": "What if I cannot sign in?", "通过登录方式、验证码和账户状态逐项确认。": "Check sign-in method, verification code, and account status.", "会员权益没有生效怎么办？": "Why are membership benefits not active?", "确认购买账户与当前登录账户保持一致。": "Make sure the purchase and sign-in accounts match.", "设备更换后如何重新绑定？": "How do I bind a replacement device?", "先解除旧设备，再按照引导完成新设备绑定。": "Unbind the old device, then follow the setup flow for the new one.",
    "首次绑定设备": "Pair your device for the first time", "完成设备开机、配对与首次同步。": "Power on, pair, and complete the first sync.", "约 2 分钟": "About 2 min", "正确佩戴设备": "Wear the device correctly", "了解合适的佩戴位置与日常检查。": "Learn the right position and daily checks.", "查看健康快照": "View a health snapshot", "快速了解宠物当日的状态变化。": "See your pet’s daily status at a glance.", "约 3 分钟": "About 3 min", "阅读健康报告": "Read a health report", "掌握报告中重点信息的查看方式。": "Learn how to review key report insights.", "使用健康助手": "Use Health Assistant", "了解健康分析与日常提醒功能。": "Learn about health analysis and daily reminders.", "创建宠物健康档案": "Create a pet health profile", "建立完整、连续的健康记录。": "Build a complete, continuous health record.", "设置电子围栏": "Set up a geofence", "为常用活动区域添加安全提醒。": "Add safety alerts for familiar activity areas.", "管理账户与会员": "Manage account & membership", "查看账户设置和会员权益。": "Review account settings and membership benefits.",
    "提交支持工单": "Submit a support ticket", "描述问题并上传相关图片，我们会尽快处理。": "Describe the issue and upload images so we can help quickly.", "查询工单进度": "Track a ticket", "通过工单编号查看当前处理状态。": "Check progress with your ticket number.", "意见与建议": "Feedback & suggestions", "向 PalEcho 提交产品建议和使用反馈。": "Share product ideas and feedback with PalEcho.", "服务说明": "Service policy", "查看服务时间、响应规则及支持范围。": "Review service hours, response rules, and support scope.", "健康助手功能升级": "Health Assistant upgrade", "优化健康分析体验与提醒呈现方式。": "Improved health analysis and alert presentation.", "功能更新": "Feature update", "健康快照功能上线": "Health Snapshot is now live", "支持更清晰地回顾每日健康状态。": "Review daily health status more clearly.", "新增设备支持": "New device support", "更多设备已支持连接与健康数据同步。": "More devices now support connection and health sync.", "维护公告": "Maintenance notice", "数据加密": "Data encryption", "设备与平台之间的数据传输采用安全加密机制。": "Device-to-platform transfers use secure encryption.", "隐私保护": "Privacy protection", "清楚说明数据用途，并由用户自主决定授权。": "We explain data use clearly and let users control consent.", "权限管理": "Permission management", "用户可管理设备、账户及数据访问权限。": "Manage access to devices, accounts, and data.", "云端同步": "Cloud sync", "查看不同设备间的健康记录同步说明。": "Learn how health records sync across devices.", "数据导出": "Data export", "按需要申请导出个人和宠物相关数据。": "Request an export of personal and pet data when needed.", "数据删除": "Data deletion", "用户可以申请删除账户及相关数据。": "Request deletion of your account and related data.",
    "官方解决方案": "Official solution", "最近更新：2026.08": "Updated: 2026.08", "解决步骤": "Steps to resolve", "仍然需要帮助？": "Still need help?", "提交工单并描述遇到的情况，我们会继续协助你。": "Submit a ticket with details and we’ll continue to help.", "官方支持内容": "Official support content", "打开 PalEcho 应用并进入对应功能页面。": "Open PalEcho and go to the relevant feature.", "按照页面中的提示完成设置或检查。": "Follow the on-screen setup or troubleshooting steps.", "如果问题仍未解决，请提交支持工单。": "If the issue remains, submit a support ticket.",
    "工单处理状态": "Ticket status", "待处理": "Open", "处理中": "In progress", "已回复": "Replied", "已解决": "Resolved", "问题类型": "Issue type", "请选择问题类型": "Select an issue type", "设备使用": "Device use", "健康数据": "Health data", "系统服务": "System service", "其他问题": "Other", "问题标题": "Issue title", "请用一句话概括遇到的问题": "Summarize the issue in one sentence", "问题描述": "Issue description", "请描述问题发生的时间、操作步骤和当前情况": "Describe when it happened, what you did, and the current status", "设备型号（可选）": "Device model (optional)", "例如：Pulse 01": "e.g. Pulse 01", "账户信息（可选）": "Account details (optional)", "手机号或邮箱": "Phone number or email", "上传图片或视频（可选）": "Upload images or video (optional)", "支持上传问题截图或相关视频，便于我们快速了解情况。": "Screenshots or videos help us understand the issue faster.", "联系方式": "Contact details", "方便我们回复你的手机号或邮箱": "Phone number or email for our reply", "请勿填写密码、支付验证码等敏感信息。提交即表示你同意我们使用上述信息处理本次支持请求。": "Do not include passwords or payment codes. Submitting means you agree that we may use this information to handle your request.", "工单提交成功": "Ticket submitted", "我们已经收到你的问题": "We’ve received your issue", "请保存下方编号，后续可用于查询处理进度。": "Save the number below to track progress.", "当前状态：待处理": "Current status: Open", "平均响应时间：15 分钟 · 服务时间：周一至周日 9:00–22:00": "Average response: 15 min · Hours: Mon–Sun, 9:00–22:00"
  };
  const zhTW = { "产品": "產品", "技术与能力": "技術與能力", "关于我们": "關於我們", "帮助中心": "幫助中心", "提交工单": "提交工單", "返回支持中心": "返回支援中心", "官方帮助中心": "官方幫助中心", "官方技术支持": "官方技術支援", "查找设备、健康数据、账户、服务及系统相关的使用帮助。": "查找裝置、健康數據、帳戶、服務與系統相關的使用幫助。", "帮助目录": "幫助目錄", "查找支持内容": "查找支援內容", "选择一个分类，查看对应的帮助与解决方案。": "選擇分類，查看對應的幫助與解決方案。", "支持范围": "支援範圍", "常见问题": "常見問題", "操作指南": "操作指南", "在线支持": "線上支援", "升级与维护": "升級與維護", "数据安全": "資料安全", "官方工单服务": "官方工單服務", "没有找到需要的内容？": "找不到需要的內容？", "平均响应时间：15 分钟": "平均回應時間：15 分鐘", "服务时间：周一至周日 9:00–22:00": "服務時間：週一至週日 9:00–22:00", "提交支持工单": "提交支援工單", "官方解决方案": "官方解決方案", "最近更新：2026.08": "最近更新：2026.08", "解决步骤": "解決步驟", "仍然需要帮助？": "仍然需要幫助？", "数据加密": "資料加密", "隐私保护": "隱私保護", "权限管理": "權限管理", "云端同步": "雲端同步", "数据导出": "資料匯出", "数据删除": "資料刪除" };
  const ja = { "产品": "製品", "技术与能力": "技術と能力", "关于我们": "私たちについて", "帮助中心": "ヘルプセンター", "提交工单": "サポートチケット", "返回支持中心": "ヘルプセンターへ戻る", "官方帮助中心": "公式ヘルプセンター", "官方技术支持": "公式テクニカルサポート", "查找设备、健康数据、账户、服务及系统相关的使用帮助。": "デバイス、健康データ、アカウント、サービス、システムの使い方を検索できます。", "帮助目录": "ヘルプ一覧", "查找支持内容": "サポートを探す", "选择一个分类，查看对应的帮助与解决方案。": "カテゴリを選び、ヘルプと解決策を確認してください。", "支持范围": "サポート範囲", "常见问题": "よくある質問", "操作指南": "ガイド", "在线支持": "オンラインサポート", "升级与维护": "アップデートとメンテナンス", "数据安全": "データセキュリティ", "官方工单服务": "公式チケットサービス", "没有找到需要的内容？": "必要な情報が見つかりませんか？", "平均响应时间：15 分钟": "平均応答時間：15分", "服务时间：周一至周日 9:00–22:00": "対応時間：月〜日 9:00〜22:00", "提交支持工单": "サポートチケットを送信", "官方解决方案": "公式ソリューション", "最近更新：2026.08": "更新：2026.08", "解决步骤": "解決手順", "仍然需要帮助？": "まだサポートが必要ですか？", "数据加密": "データ暗号化", "隐私保护": "プライバシー保護", "权限管理": "権限管理", "云端同步": "クラウド同期", "数据导出": "データエクスポート", "数据删除": "データ削除" };
  Object.assign(zhTW, {
    "PalEcho 为用户提供覆盖设备、数据、账户及平台服务的官方支持。": "PalEcho 為使用者提供涵蓋裝置、資料、帳戶與平台服務的官方支援。", "快速查看用户最常遇到的问题。": "快速查看使用者最常遇到的問題。", "从首次使用到日常管理，快速了解 PalEcho 的主要功能。": "從首次使用到日常管理，快速了解 PalEcho 的主要功能。", "通过官方渠道提交问题并获得帮助。": "透過官方管道提交問題並獲得幫助。", "查看最新版本、功能更新及维护安排。": "查看最新版本、功能更新與維護安排。", "了解 PalEcho 如何保护设备数据、健康信息与账户安全。": "了解 PalEcho 如何保護裝置資料、健康資訊與帳戶安全。",
    "查看设备连接、佩戴、充电及使用帮助。": "查看裝置連線、佩戴、充電與使用幫助。", "了解健康分析、异常提醒及报告功能。": "了解健康分析、異常提醒與報告功能。", "查看数据同步、健康档案和历史记录。": "查看資料同步、健康檔案與歷史記錄。", "了解陪伴互动、状态记录与日常功能。": "了解陪伴互動、狀態記錄與日常功能。", "处理订单查询、配送与售后相关问题。": "處理訂單查詢、配送與售後相關問題。", "管理登录信息、会员权益与账户设置。": "管理登入資訊、會員權益與帳戶設定。", "查看定位权限、电子围栏与防丢帮助。": "查看定位權限、電子圍籬與防丟幫助。", "了解版本更新、功能变化与使用要求。": "了解版本更新、功能變化與使用要求。",
    "设备无法连接怎么办？": "裝置無法連線怎麼辦？", "从设备电量、蓝牙权限与网络环境开始排查。": "從裝置電量、藍牙權限與網路環境開始排查。", "为什么没有健康数据？": "為什麼沒有健康資料？", "检查佩戴、同步状态和账户绑定情况。": "檢查佩戴、同步狀態與帳戶綁定情況。", "定位出现偏差怎么办？": "定位出現偏差怎麼辦？", "了解定位权限与室内外环境的影响。": "了解定位權限與室內外環境的影響。", "健康报告没有更新怎么办？": "健康報告沒有更新怎麼辦？", "确认同步状态和报告生成时间。": "確認同步狀態與報告產生時間。", "账号无法登录怎么办？": "帳號無法登入怎麼辦？", "通过登录方式、验证码和账户状态逐项确认。": "逐項確認登入方式、驗證碼與帳戶狀態。",
    "首次绑定设备": "首次綁定裝置", "完成设备开机、配对与首次同步。": "完成裝置開機、配對與首次同步。", "正确佩戴设备": "正確佩戴裝置", "查看健康快照": "查看健康快照", "阅读健康报告": "閱讀健康報告", "使用健康助手": "使用健康助手", "创建宠物健康档案": "建立寵物健康檔案", "设置电子围栏": "設定電子圍籬", "管理账户与会员": "管理帳戶與會員", "约 2 分钟": "約 2 分鐘", "约 3 分钟": "約 3 分鐘"
  });
  Object.assign(ja, {
    "PalEcho 为用户提供覆盖设备、数据、账户及平台服务的官方支持。": "PalEcho はデバイス、データ、アカウント、プラットフォームサービスを公式にサポートします。", "快速查看用户最常遇到的问题。": "よくある問題をすぐに確認できます。", "从首次使用到日常管理，快速了解 PalEcho 的主要功能。": "初回設定から日常管理まで、PalEcho の主な機能を確認できます。", "通过官方渠道提交问题并获得帮助。": "公式窓口から問題を送信し、サポートを受けられます。", "查看最新版本、功能更新及维护安排。": "最新バージョン、機能更新、メンテナンス予定を確認できます。", "了解 PalEcho 如何保护设备数据、健康信息与账户安全。": "PalEcho がデバイスデータ、健康情報、アカウントを守る方法を確認できます。",
    "查看设备连接、佩戴、充电及使用帮助。": "接続、装着、充電、使用方法を確認できます。", "了解健康分析、异常提醒及报告功能。": "健康分析、異常通知、レポート機能を確認できます。", "查看数据同步、健康档案和历史记录。": "データ同期、健康プロフィール、履歴を確認できます。", "了解陪伴互动、状态记录与日常功能。": "ふれあい、状態記録、日常機能を確認できます。", "处理订单查询、配送与售后相关问题。": "注文、配送、アフターサービスに関する問題を解決します。", "管理登录信息、会员权益与账户设置。": "ログイン情報、会員特典、アカウント設定を管理します。", "查看定位权限、电子围栏与防丢帮助。": "位置情報の権限、ジオフェンス、紛失対策を確認できます。", "了解版本更新、功能变化与使用要求。": "バージョン更新、変更点、利用条件を確認できます。",
    "设备无法连接怎么办？": "デバイスを接続できない場合", "从设备电量、蓝牙权限与网络环境开始排查。": "バッテリー、Bluetooth 権限、ネットワークから確認します。", "为什么没有健康数据？": "健康データがない場合", "检查佩戴、同步状态和账户绑定情况。": "装着状態、同期、アカウント連携を確認します。", "定位出现偏差怎么办？": "位置情報がずれる場合", "了解定位权限与室内外环境的影响。": "権限と屋内外の環境による影響を確認します。", "健康报告没有更新怎么办？": "健康レポートが更新されない場合", "确认同步状态和报告生成时间。": "同期状態とレポート生成時刻を確認します。", "账号无法登录怎么办？": "ログインできない場合", "通过登录方式、验证码和账户状态逐项确认。": "ログイン方法、認証コード、アカウント状態を確認します。",
    "首次绑定设备": "デバイスを初めてペアリング", "完成设备开机、配对与首次同步。": "電源を入れ、ペアリングと初回同期を完了します。", "正确佩戴设备": "デバイスを正しく装着", "查看健康快照": "ヘルススナップショットを見る", "阅读健康报告": "健康レポートを読む", "使用健康助手": "ヘルスアシスタントを使う", "创建宠物健康档案": "ペットの健康プロフィールを作成", "设置电子围栏": "ジオフェンスを設定", "管理账户与会员": "アカウントと会員を管理", "约 2 分钟": "約2分", "约 3 分钟": "約3分"
  });
  const dictionaries = { "zh-CN": {}, "zh-TW": zhTW, en, ja, ko: en };
  const names = { "zh-CN": "简体中文", "zh-TW": "繁體中文", en: "English", ja: "日本語", ko: "한국어" };
  const locale = () => { const value = localStorage.getItem("palecho_lang"); return dictionaries[value] ? value : "zh-CN"; };
  const t = (value) => dictionaries[locale()][value] || value;
  window.PalEchoSupportI18n = { t, locale, names };
  const mountPicker = () => {
    if (!document.body || document.querySelector(".palecho-language-picker")) return;
    if (!document.getElementById("palecho-language-picker-style")) {
      const style = document.createElement("style");
      style.id = "palecho-language-picker-style";
      style.textContent = ".palecho-language-picker{position:fixed;top:22px;right:28px;z-index:2000}.palecho-language-picker select{padding:8px 28px 8px 11px;border:1px solid rgba(25,26,27,.12);border-radius:999px;background:rgba(255,255,252,.82);color:#555a57;font:12px Inter,-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif;outline:0}.palecho-language-picker select:focus-visible{border-color:rgba(54,118,201,.6);box-shadow:0 0 0 3px rgba(54,118,201,.1)}@media(max-width:760px){.palecho-language-picker{top:14px;right:18px}.palecho-language-picker select{max-width:100px}}";
      document.head.append(style);
    }
    const label = document.createElement("label"); label.className = "palecho-language-picker"; label.setAttribute("aria-label", "Language");
    const select = document.createElement("select");
    Object.entries(names).forEach(([value, name]) => { const option = document.createElement("option"); option.value = value; option.textContent = name; select.append(option); });
    select.value = locale(); select.addEventListener("change", () => { localStorage.setItem("palecho_lang", select.value); location.reload(); });
    label.append(select); document.body.append(label); document.documentElement.lang = locale();
  };
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", mountPicker); else mountPicker();
})();
